// <auto-generated />
using FirstApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstApi.Migrations
{
    [DbContext(typeof(FirstApiContext))]
    partial class FirstApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FirstApi.Model.LevelPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LevelPriorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "L",
                            Name = "Low"
                        },
                        new
                        {
                            Id = 2,
                            Code = "M",
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Code = "H",
                            Name = "High"
                        });
                });

            modelBuilder.Entity("FirstApi.Model.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isCompleted");

                    b.Property<int?>("LevelPriorityId")
                        .HasColumnType("int")
                        .HasColumnName("level_priority_id");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("task");

                    b.HasKey("Id");

                    b.HasIndex("LevelPriorityId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("FirstApi.Model.Todo", b =>
                {
                    b.HasOne("FirstApi.Model.LevelPriority", "LevelPriority")
                        .WithMany()
                        .HasForeignKey("LevelPriorityId");

                    b.Navigation("LevelPriority");
                });
#pragma warning restore 612, 618
        }
    }
}
